import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
import NavBar from "@/components/NavBar/page";
import { Toaster } from "@/components/ui/sonner";

const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["300","400","600","700"]
})

export const metadata: Metadata = {
  title: "Ravi Kumar Chavva",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      <link rel="icon" href="/icon.png" />
      </head>
      <body 
        className={cn(
          "min-h-screen bg-background font-sans antialiased ",
          fontPoppins.className
        )}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavBar />
              {children}
              <Toaster />
          </ThemeProvider>
      </body>
    </html>
  );
}
